# Generated by Django 5.2.7 on 2025-10-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch_code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Branch Code",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Branch Name"
                    ),
                ),
                (
                    "branch_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Branch Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "Branch",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "registration_no",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Registration No",
                    ),
                ),
                (
                    "date_of_admission",
                    models.DateField(verbose_name="Date of Admission"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "Student",
            },
        ),
        migrations.CreateModel(
            name="ParentInfo",
            fields=[
                (
                    "parent_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Parent ID"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="Father's Name"),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=50, verbose_name="Mother's Name"),
                ),
                (
                    "father_occupation",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Father's Occupation",
                    ),
                ),
                (
                    "mother_occupation",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mother's Occupation",
                    ),
                ),
                (
                    "father_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Father's Mobile",
                    ),
                ),
                (
                    "mother_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Mother's Mobile",
                    ),
                ),
                (
                    "alternate_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Alternate Mobile",
                    ),
                ),
                (
                    "registration_no",
                    models.ForeignKey(
                        db_column="Registration_No",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Information",
                "verbose_name_plural": "Parent Information",
                "db_table": "Parent_Info",
            },
        ),
        migrations.CreateModel(
            name="FeeDetails",
            fields=[
                (
                    "fee_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Fee ID"
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Fees",
                    ),
                ),
                (
                    "number_of_installments",
                    models.IntegerField(
                        default=1, verbose_name="Number of Installments"
                    ),
                ),
                (
                    "fees_per_installment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Fees per Installment",
                    ),
                ),
                (
                    "fees_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Fees Remaining",
                    ),
                ),
                (
                    "registration_no",
                    models.ForeignKey(
                        db_column="Registration_No",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Details",
                "verbose_name_plural": "Fee Details",
                "db_table": "Fee_Details",
            },
        ),
        migrations.CreateModel(
            name="AcademicInfo",
            fields=[
                (
                    "academic_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Academic ID"
                    ),
                ),
                (
                    "enrolled_course",
                    models.CharField(max_length=50, verbose_name="Enrolled Course"),
                ),
                (
                    "percentage_previous_exam",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Previous Exam %",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="School Name",
                    ),
                ),
                (
                    "branch_code",
                    models.ForeignKey(
                        db_column="Branch_Code",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "registration_no",
                    models.ForeignKey(
                        db_column="Registration_No",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Information",
                "verbose_name_plural": "Academic Information",
                "db_table": "Academic_Info",
            },
        ),
    ]
