# Generated by Django 4.2.7 on 2026-06-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_messageanalyticssummary_whatsappmessageanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='parentinfo',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='parentinfo',
            name='mother_occupation',
        ),
    ]
