# Generated by Django 4.2.7 on 2026-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsapp_fallback_tracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAnalyticsSummary',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessageAnalytics',
        ),
    ]
