# Generated by Django 5.2.7 on 2025-10-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.OneToOneField(
                db_column="Registration_No",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academicinfo",
                to="core.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="feedetails",
            name="registration_no",
            field=models.OneToOneField(
                db_column="Registration_No",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedetails",
                to="core.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="parentinfo",
            name="registration_no",
            field=models.OneToOneField(
                db_column="Registration_No",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parentinfo",
                to="core.student",
                verbose_name="Student",
            ),
        ),
    ]
