# Generated by Django 5.2.7 on 2025-10-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_academicinfo_registration_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedetails",
            name="first_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="First Installment",
            ),
        ),
        migrations.AddField(
            model_name="feedetails",
            name="first_installment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="First Installment Date"
            ),
        ),
        migrations.AddField(
            model_name="feedetails",
            name="second_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Second Installment",
            ),
        ),
        migrations.AddField(
            model_name="feedetails",
            name="second_installment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Second Installment Date"
            ),
        ),
        migrations.AddField(
            model_name="feedetails",
            name="third_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Third Installment",
            ),
        ),
        migrations.AddField(
            model_name="feedetails",
            name="third_installment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Third Installment Date"
            ),
        ),
    ]
