# Generated by Django 5.2.7 on 2025-10-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedetails_first_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='academic_id',
            field=models.AutoField(db_column='Academic_ID', primary_key=True, serialize=False, verbose_name='Academic ID'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='enrolled_course',
            field=models.CharField(db_column='Enrolled_Course', max_length=50, verbose_name='Enrolled Course'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='percentage_previous_exam',
            field=models.DecimalField(blank=True, db_column='Percentage_Previous_Exam', decimal_places=2, max_digits=5, null=True, verbose_name='Previous Exam %'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='school_name',
            field=models.CharField(blank=True, db_column='School_Name', max_length=100, null=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(db_column='Branch_Code', max_length=10, primary_key=True, serialize=False, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_location',
            field=models.CharField(blank=True, db_column='Branch_Location', max_length=100, null=True, verbose_name='Branch Location'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(db_column='Branch_Name', max_length=50, unique=True, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='fee_id',
            field=models.AutoField(db_column='Fee_ID', primary_key=True, serialize=False, verbose_name='Fee ID'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='fees_per_installment',
            field=models.DecimalField(db_column='Fees_Per_Installment', decimal_places=2, default=0, max_digits=10, verbose_name='Fees per Installment'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='fees_remaining',
            field=models.DecimalField(db_column='Fees_Remaining', decimal_places=2, default=0, max_digits=10, verbose_name='Fees Remaining'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='first_installment',
            field=models.DecimalField(blank=True, db_column='first_installment', decimal_places=2, max_digits=10, null=True, verbose_name='First Installment'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='first_installment_date',
            field=models.DateField(blank=True, db_column='first_installment_date', null=True, verbose_name='First Installment Date'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='number_of_installments',
            field=models.IntegerField(db_column='Number_of_Installments', default=1, verbose_name='Number of Installments'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='second_installment',
            field=models.DecimalField(blank=True, db_column='second_installment', decimal_places=2, max_digits=10, null=True, verbose_name='Second Installment'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='second_installment_date',
            field=models.DateField(blank=True, db_column='second_installment_date', null=True, verbose_name='Second Installment Date'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='third_installment',
            field=models.DecimalField(blank=True, db_column='third_installment', decimal_places=2, max_digits=10, null=True, verbose_name='Third Installment'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='third_installment_date',
            field=models.DateField(blank=True, db_column='third_installment_date', null=True, verbose_name='Third Installment Date'),
        ),
        migrations.AlterField(
            model_name='feedetails',
            name='total_fees',
            field=models.DecimalField(db_column='Total_Fees', decimal_places=2, default=0, max_digits=10, verbose_name='Total Fees'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='alternate_mobile',
            field=models.CharField(blank=True, db_column='Alternate_Mobile', max_length=15, null=True, verbose_name='Alternate Mobile'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_mobile',
            field=models.CharField(blank=True, db_column='Father_Mobile', max_length=15, null=True, unique=True, verbose_name="Father's Mobile"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_name',
            field=models.CharField(db_column='Father_Name', max_length=50, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='father_occupation',
            field=models.CharField(blank=True, db_column='Father_Occupation', max_length=50, null=True, verbose_name="Father's Occupation"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_mobile',
            field=models.CharField(blank=True, db_column='Mother_Mobile', max_length=15, null=True, unique=True, verbose_name="Mother's Mobile"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_name',
            field=models.CharField(db_column='Mother_Name', max_length=50, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_occupation',
            field=models.CharField(blank=True, db_column='Mother_Occupation', max_length=50, null=True, verbose_name="Mother's Occupation"),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='parent_id',
            field=models.AutoField(db_column='Parent_ID', primary_key=True, serialize=False, verbose_name='Parent ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(db_column='Date_of_Admission', verbose_name='Date of Admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(db_column='Date_of_Birth', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='First_Name', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_column='Gender', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='Last_Name', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, db_column='Middle_Name', max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.IntegerField(db_column='Registration_No', primary_key=True, serialize=False, verbose_name='Registration No'),
        ),
        migrations.AlterModelTable(
            name='academicinfo',
            table='academic_info',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
        migrations.AlterModelTable(
            name='feedetails',
            table='fee_details',
        ),
        migrations.AlterModelTable(
            name='parentinfo',
            table='parent_info',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.CreateModel(
            name='CustomMessageLog',
            fields=[
                ('message_id', models.AutoField(db_column='Message_ID', primary_key=True, serialize=False, verbose_name='Message ID')),
                ('message_text', models.TextField(db_column='Message_Text', verbose_name='Message Text')),
                ('attachment', models.CharField(blank=True, db_column='Attachment', max_length=255, null=True, verbose_name='Attachment Path')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp', verbose_name='Timestamp')),
                ('sent_status', models.CharField(db_column='Sent_Status', default='PENDING', max_length=20, verbose_name='Sent Status')),
                ('student', models.ForeignKey(db_column='Student_ID', on_delete=django.db.models.deletion.CASCADE, related_name='custom_messages', to='core.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Custom Message Log',
                'verbose_name_plural': 'Custom Message Logs',
                'db_table': 'custom_message_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
