# Generated by Django 5.2.7 on 2025-10-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_academicinfo_academic_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeInstallments",
            fields=[
                (
                    "installment_id",
                    models.AutoField(
                        db_column="Installment_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Installment ID",
                    ),
                ),
                (
                    "installment_no",
                    models.IntegerField(
                        db_column="Installment_No", verbose_name="Installment Number"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount",
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(db_column="Due_Date", verbose_name="Due Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Due", "Due"),
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                        ],
                        db_column="Status",
                        default="Due",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        db_column="Paid_Date",
                        null=True,
                        verbose_name="Paid Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="Created_At",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="Updated_At", verbose_name="Updated At"
                    ),
                ),
                (
                    "registration_no",
                    models.ForeignKey(
                        db_column="Registration_No",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="core.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Installment",
                "verbose_name_plural": "Fee Installments",
                "db_table": "fee_installments",
                "ordering": ["registration_no", "installment_no"],
                "unique_together": {("registration_no", "installment_no")},
            },
        ),
    ]
