# Generated by Django 5.2.7 on 2025-10-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_feeinstallments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentinfo",
            name="father_mobile",
            field=models.CharField(
                blank=True,
                db_column="Father_Mobile",
                max_length=15,
                null=True,
                verbose_name="Father's Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="parentinfo",
            name="mother_mobile",
            field=models.CharField(
                blank=True,
                db_column="Mother_Mobile",
                max_length=15,
                null=True,
                verbose_name="Mother's Mobile",
            ),
        ),
    ]
