# Generated by Django 5.2.7 on 2025-10-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_parentinfo_father_mobile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAnalyticsSummary",
            fields=[
                (
                    "summary_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Summary ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_messages_sent",
                    models.IntegerField(default=0, verbose_name="Total Messages Sent"),
                ),
                (
                    "birthday_messages",
                    models.IntegerField(default=0, verbose_name="Birthday Messages"),
                ),
                (
                    "reminder_1_messages",
                    models.IntegerField(default=0, verbose_name="Reminder 1 Messages"),
                ),
                (
                    "reminder_2_messages",
                    models.IntegerField(default=0, verbose_name="Reminder 2 Messages"),
                ),
                (
                    "reminder_3_messages",
                    models.IntegerField(default=0, verbose_name="Reminder 3 Messages"),
                ),
                (
                    "last_reminder_messages",
                    models.IntegerField(
                        default=0, verbose_name="Last Reminder Messages"
                    ),
                ),
                (
                    "final_notice_messages",
                    models.IntegerField(
                        default=0, verbose_name="Final Notice Messages"
                    ),
                ),
                (
                    "messages_delivered",
                    models.IntegerField(default=0, verbose_name="Messages Delivered"),
                ),
                (
                    "messages_read",
                    models.IntegerField(default=0, verbose_name="Messages Read"),
                ),
                (
                    "messages_failed",
                    models.IntegerField(default=0, verbose_name="Messages Failed"),
                ),
                (
                    "total_responses",
                    models.IntegerField(default=0, verbose_name="Total Responses"),
                ),
                (
                    "payment_confirmations",
                    models.IntegerField(
                        default=0, verbose_name="Payment Confirmations"
                    ),
                ),
                (
                    "queries_received",
                    models.IntegerField(default=0, verbose_name="Queries Received"),
                ),
                (
                    "delivery_rate",
                    models.FloatField(default=0.0, verbose_name="Delivery Rate (%)"),
                ),
                (
                    "read_rate",
                    models.FloatField(default=0.0, verbose_name="Read Rate (%)"),
                ),
                (
                    "response_rate",
                    models.FloatField(default=0.0, verbose_name="Response Rate (%)"),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        default=0.0, verbose_name="Average Response Time (hours)"
                    ),
                ),
                (
                    "highly_engaged_parents",
                    models.IntegerField(
                        default=0, verbose_name="Highly Engaged Parents"
                    ),
                ),
                (
                    "average_engagement_score",
                    models.FloatField(
                        default=0.0, verbose_name="Average Engagement Score"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Message Analytics Summary",
                "verbose_name_plural": "Message Analytics Summaries",
                "db_table": "message_analytics_summary",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageAnalytics",
            fields=[
                (
                    "analytics_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Analytics ID"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday Message"),
                            ("reminder_1", "Reminder 1 (-3 Days)"),
                            ("reminder_2", "Reminder 2 (+1 Day)"),
                            ("reminder_3", "Reminder 3 (+4 Days)"),
                            ("last_reminder", "Last Reminder (+7 Days)"),
                            ("discontinuation", "Final Notice (+10 Days)"),
                            ("custom", "Custom Message"),
                        ],
                        max_length=20,
                        verbose_name="Message Type",
                    ),
                ),
                ("message_content", models.TextField(verbose_name="Message Content")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[("Father", "Father"), ("Mother", "Mother")],
                        max_length=10,
                        verbose_name="Parent Type",
                    ),
                ),
                (
                    "sent_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sent Timestamp"
                    ),
                ),
                (
                    "delivery_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Timestamp"
                    ),
                ),
                (
                    "read_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Read Timestamp"
                    ),
                ),
                (
                    "response_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Timestamp"
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="SENT",
                        max_length=10,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Response"),
                            ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                            ("QUERY", "Query/Question"),
                            ("ACKNOWLEDGMENT", "Acknowledgment"),
                            ("COMPLAINT", "Complaint"),
                            ("OTHER", "Other Response"),
                        ],
                        default="NONE",
                        max_length=20,
                        verbose_name="Response Type",
                    ),
                ),
                (
                    "response_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Response Content"
                    ),
                ),
                (
                    "delivery_time_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Delivery Time (seconds)"
                    ),
                ),
                (
                    "read_time_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Read Time (seconds)"
                    ),
                ),
                (
                    "response_time_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Response Time (seconds)"
                    ),
                ),
                (
                    "is_engaged",
                    models.BooleanField(default=False, verbose_name="Parent Engaged"),
                ),
                (
                    "engagement_score",
                    models.FloatField(default=0.0, verbose_name="Engagement Score"),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.feeinstallments",
                        verbose_name="Related Installment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_analytics",
                        to="core.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message Analytics",
                "verbose_name_plural": "WhatsApp Message Analytics",
                "db_table": "whatsapp_message_analytics",
                "ordering": ["-sent_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message_type", "delivery_status"],
                        name="whatsapp_me_message_8fe3cf_idx",
                    ),
                    models.Index(
                        fields=["sent_timestamp"], name="whatsapp_me_sent_ti_8e0951_idx"
                    ),
                    models.Index(
                        fields=["student", "message_type"],
                        name="whatsapp_me_student_b3483b_idx",
                    ),
                ],
            },
        ),
    ]
